Add SSH config customization, static IP support through AWS

diff --git a/chart/values.yaml b/chart/values.yaml
--- a/chart/values.yaml
+++ b/chart/values.yaml
@@ -4,10 +4,23 @@ nfs-server-provisioner:
     size: 10Gi
 
 ssh:
-  enabled: false
+  enabled: true
   image:
     name: astronomycommons/jupyterhub-ssh
-    tag: deploy
+    tag: 0.0.4
+  hostname: ssh
+  config:
+    jump:
+      ssh_config:
+      sshd_config: 
+        PasswordAuthentication: "no"
+        ClientAliveInterval: 15
+    user:
+      ssh_config:
+      sshd_config: 
+        PasswordAuthentication: "no"
+        ClientAliveInterval: 15
+
   # consistent with rest of the JupyterHub
   admin_users:
 
@@ -27,6 +40,8 @@ mariadb:
       mysql -P 3306 -uroot -p$MARIADB_ROOT_PASSWORD -e "use $MARIADB_DATABASE; source /tmp/hive-schema-2.3.0.mysql.sql;"
 
 jupyterhub:
+  custom:
+    host_tag: jupyter
   rbac:
     enabled: true
   hub:
@@ -37,28 +52,34 @@ jupyterhub:
     extraConfig:
       ssh_config: |
         from z2jh import get_config
-        if get_config("ssh.enabled"):
-          def modify_pod_hook(spawner, pod):
-            pod.spec.subdomain = "notebooks"
-            pod.spec.hostname = spawner._expand_user_properties("jupyter-{username}--{servername}")
-            return pod
+        if get_config("custom.host_tag"):
+          host_tag = get_config("custom.host_tag")
+        else:
+          host_tag = "jupyter"
+        def modify_pod_hook(spawner, pod):
+          pod.spec.subdomain = "notebooks"
+          if spawner._expand_user_properties("{servername}"):
+            pod.spec.hostname = spawner._expand_user_properties(host_tag + "-{username}-{servername}")
+          else:
+            pod.spec.hostname = spawner._expand_user_properties(host_tag + "-{username}")
+          return pod
 
-          c.KubeSpawner.modify_pod_hook = modify_pod_hook
+        c.KubeSpawner.modify_pod_hook = modify_pod_hook
 
-          c.KubeSpawner.extra_container_config = {
-            'ports': [
-              {
-                'containerPort': 8888,
-                'name': 'notebook-port',
-                'protocol': 'TCP'
-              },
-              {
-                'containerPort': 22, 
-                'name': 'ssh-port', 
-                'protocol': 'TCP'
-              }
-            ]
-          }
+        c.KubeSpawner.extra_container_config = {
+          'ports': [
+            {
+              'containerPort': 8888,
+              'name': 'notebook-port',
+              'protocol': 'TCP'
+            },
+            {
+              'containerPort': 22, 
+              'name': 'ssh-port', 
+              'protocol': 'TCP'
+            }
+          ]
+        }
 
       run_user_as_root: |
         c.KubeSpawner.uid = 0
@@ -100,7 +121,7 @@ jupyterhub:
   singleuser:
     image: 
       name: astronomycommons/public-hub-singleuser
-      tag: deploy
+      tag: 0.5.0
       pullPolicy: Always
     # assigns the notebook pod the service account called jupyter-spark-serviceaccount in the k8s cluster
     # this service account is created if rbac.enabled is set to true in this Helm chart
@@ -135,6 +156,9 @@ jupyterhub:
       - name: "nfs-kernels-volume"
         persistentVolumeClaim:
           claimName: "nfs-kernels"
+      - name: "ssh-config-volume"
+        configMap:
+          name: "ssh-config-map"
       extraVolumeMounts:
       # mount spark configurations from configMap
       # mount spark-defaults.conf to spark-defaults.conf.static
@@ -154,11 +178,11 @@ jupyterhub:
       - name: "spark-config-volume"
         mountPath: "/opt/axs/conf/executor.yaml.static"
         subPath: "executor.yaml"
-      # mount the efs-backed filesystem to /nfs
-      # creates a folder for the user in /nfs and /nfs contains all other users
+      # mount NFS
+      # creates a folder for the user in /home and /home contains all other users
       - name: "nfs-homes-volume"
         mountPath: "/home/{username}"
-        # subPath creates a folder within the efs filesystem for the user
+        # subPath creates a folder within the NFS filesystem for the user
         subPath: "{username}"
       - name: "nfs-homes-volume"
         mountPath: "/home"
@@ -171,6 +195,12 @@ jupyterhub:
         mountPath: "/usr/local/bin/start-notebook.d"
       - name: "before-notebook-volume"
         mountPath: "/usr/local/bin/before-notebook.d"
+      - name: ssh-config-volume
+        subPath: ssh_config_user
+        mountPath: /etc/_ssh/ssh_config.d/chart.conf
+      - name: ssh-config-volume
+        subPath: sshd_config_user
+        mountPath: /etc/_ssh/sshd_config.d/chart.conf
 
 spark-defaults.conf:
   000-s3-defaults: |
@@ -242,38 +272,91 @@ start-notebook:
     merge "$SPARK_HOME/conf/executor.yaml"
 
 before-notebook:
-  ssh-setup.sh: |
+  001-ssh-setup.sh: |
+    echo "Starting SSH setup"
     # load ssh config from NFS
     server_config_dir="/home/admin/ssh/users/$NB_USER"
-    if [ ! -d $server_config_dir ]
+    user_ssh_dir="/home/$NB_USER/.ssh"
+    sudo -u $NB_USER mkdir -p ${user_ssh_dir}
+    if [ ! -d ${server_config_dir} ]
     then
-        # Back up host keys and config to NFS
-        mkdir -p $server_config_dir
-        cp -r /etc/ssh/* $server_config_dir/.
+      echo "${server_config_dir} does not exist. Creating it and copying over contents of /etc/ssh/"
+      # Back up host keys and config to NFS
+      mkdir -p ${server_config_dir}
+      cp -r /etc/ssh/* ${server_config_dir}/.
     fi
     # remove host keys and config from container
     rm -rf /etc/ssh
     # link to host keys and config on NFS
-    ln -s $server_config_dir /etc/ssh
+    ln -s ${server_config_dir} /etc/ssh
 
     # (re)generate missing host keys
     ssh-keygen -A
 
     # Set-up public/private keys for user
-    if test -f "/home/$NB_USER/.ssh/id_rsa"; then
+    if test -f "${user_ssh_dir}/id_rsa"; then
       echo "ssh key-pair already exists"
     else
       echo "creating ssh key-pair"
-      ssh-keygen -t rsa -q -f "/home/$NB_USER/.ssh/id_rsa" -N "" || echo "could not create ssh key pair!"
-      cat /home/$NB_USER/.ssh/id_rsa.pub >> /home/$NB_USER/.ssh/authorized_keys
+      sudo -u $NB_USER ssh-keygen -t rsa -q -f "${user_ssh_dir}/id_rsa" -N "" || echo "could not create ssh key pair!"
+      cat ${user_ssh_dir}/id_rsa.pub >> ${user_ssh_dir}/authorized_keys
+      chown -R $NB_USER:$NB_GID ${user_ssh_dir}
     fi
 
     # restrict logins to only the notebook user
-    echo "AllowUsers $NB_USER" >> /etc/ssh/sshd_config
+    if grep "AllowUsers $NB_USER" /etc/ssh/sshd_config 2>&1 > /dev/null; then
+      echo "AllowUsers $NB_USER exists in /etc/ssh/sshd_config"
+    else
+      echo "Adding AllowUsers $NB_USER to /etc/ssh/sshd_config"
+      echo "AllowUsers $NB_USER" >> /etc/ssh/sshd_config
+    fi
 
-    # start the SSH service
+    # add config specified via Helm chart
+    if [ -d /etc/_ssh ]; then
+        cat /etc/_ssh/ssh_config.d/chart.conf
+        cp /etc/_ssh/ssh_config.d/chart.conf /etc/ssh/ssh_config.d/.
+        cat /etc/_ssh/sshd_config.d/chart.conf
+        cp /etc/_ssh/sshd_config.d/chart.conf /etc/ssh/sshd_config.d/.
+    fi
+
+    # ensure /run/sshd
+    mkdir -p /run/sshd
+    # print sshd config
+    echo "sshd config:"
+    sshd -T
+    # start ssh service
     service ssh start
 
+    # add host key fingerprints to known_hosts
+    sudo -u $NB_USER touch ${user_ssh_dir}/known_hosts
+    hosts="localhost $(hostname).notebooks ssh"
+    for host in ${hosts}; do
+      if cat "${user_ssh_dir}/known_hosts" | awk '{print $1}' | grep "${host}" 2>&1 > /dev/null; then
+        echo "Host key for ${host} already in ${user_ssh_dir}/known_hosts"
+      else
+        if nslookup ${host} 2>&1 > /dev/null; then
+          echo "Adding host key for ${host} to ${user_ssh_dir}/known_hosts"
+          ssh-keyscan ${host} 2> /dev/null >> ${user_ssh_dir}/known_hosts
+        else
+          echo "Cannot find host ${host}"
+        fi
+      fi
+    done
+
+    # ensure bash shell on login
+    chsh -s /bin/bash $NB_USER
+  
+  002-skel.sh: |
+    files=".bash_logout .profile .bashrc"
+    for file in ${files}; do
+      user_file=/home/${NB_USER}/${file}
+      if [ -f ${user_file} ]; then
+        echo "${user_file} exists"
+      else
+        sudo -u $NB_USER cp /etc/skel/${file} ${user_file}
+      fi
+    done
+    
 nfs-pvcs:
   nfs:
     name: nfs
